### PR TITLE
#1061 : make item layout more flexible to width, fix action inconsist…

### PR DESCRIPTION
**Pull request by dominiksteiner**
…encies, fix tab cursor

@amirmehmood @joncodo please review

this removed the fix width we had on the title/description and uses a table layout. Right now only teamOne and salesforce use those styles but especially for teamOne it is useful as it will expand the title if an item only has the launch browser quick action.

### CODE REVIEW

**Comment by joncodo** [comment]
lgtm

**Comment by amirmehmood** [comment]
@dominiksteiner I think we can fix it without using `table-layout` which is only recommended when we want to layout things in rows and columns. `table-layout` is also little verbose because we need an extra wrapper i.e. `table-row`. Can you try `flex-box` because I think it has answer to these problems too. Let me know if that makes sense?

**Comment by dominiksteiner** [comment]
i don't have too much experience with flex-box, so that would be your call @amirmehmood. We would also need something by the end of today I guess so we can deploy and have it ready for testing for Monday. If you think you can do it let me know and I'm happy to wait.

**Comment by dominiksteiner** [comment]
@amirmehmood moved it to flex-box layout, can you check now?

**Pull request merged**
